basePath: /api/v1
host: 127.0.0.1:8084
info:
  contact:
    name: liwenzhou
    url: http://www.liwenzhou.com
  description: bluebell
  title: bluebell项目接口文档
  version: "1.0"
paths: {}
swagger: "2.0"
